server:
  port: 8899
spring:
  datasource:
   url:  jdbc:mysql://localhost:3306/microservices
   username: root
   password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     format_sql: true
  application:
    name: coupon-service
  config:
    import:
    - optional:configserver:http://localhost:8888/

     
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /myActuator

  endpoint:
    shutdown:
      enabled: true
    
      
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

