server:
  port: 9090
   
spring:
  datasource:
   url:  jdbc:mysql://localhost:3306/microservices
   username: root
   password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     format_sql: true
  application:
    name: product-service
  config:
    import:
    - optional:configserver:http://localhost:8888/
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude: health
      base-path: /myActuator

  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    
resilience4j:
  retry:
    instances:
      productapi:
       max-attempts: 3
       wait-duration: 20s
          