#server.port=9090

#spring.datasource.url= jdbc:mysql://localhost:3306/javabatch

#spring.datasource.username=root

#spring.datasource.password=Temp1234

#spring.jpa.hibernate.ddl-auto=create


server:
  port: 1212
   
spring:
  datasource:
   url:  jdbc:mysql://localhost:3306/javabatch
   username: root
   password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     format_sql: true
    